version: '3.8'

services:
  app:
    container_name: library-system-app
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "run", "start:dev"]
    env_file:
      - .env
    networks:
      - library-network



  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - library-network

volumes:
  db_data:

networks:
  library-network:
